GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzEwODQzMzQ3fQ.f9fxtW2RTzpbbcbTlzqMaOpBd89ZaHWh9Qmn0YBBapA

###

GET http://localhost:3000/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzEwODQzMzQ3fQ.f9fxtW2RTzpbbcbTlzqMaOpBd89ZaHWh9Qmn0YBBapA

###

GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzEwODQ0NDIwfQ.HI-5qdTXElQ0kLPAeESzzc1VkjA6rgihqfUJF3pgbL8

###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rajesh1234",
    "password": "raj@4567",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}